[[this_includes]]
file = 'configurations/pi0ana/selected/reco_variables_NC.toml'

[[this_includes]]
file = 'configurations/pi0ana/samples.toml'
choose = {'samples' = ['mc_nc']}

[[this_includes]]
file = 'configurations/pi0ana/styles.toml'

[output]
path = '/exp/icarus/app/users/lkashur/SPINEAna/spine_anaplot_tools/spineplot/'

[analysis]
ordinate_sample = 'mc_nc'
category_branch = 'category_topology'
category_assignment = [[0], [1], [2], [3], [4], [5]]
category_labels = ['0$\mu$1$\pi^{0}$', '0$\mu$1$\pi^{0}$ (OOPS)', '0$\mu$N$\pi^{0}$', 'CC1$\pi^{0}$', 'Other $\nu$', 'Cosmic']
category_colors = ['#1b9e77', '#dea0fd', '#4c78a8', '#e5c494', '#e45756', '#17becf']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram']

[[figure]]
name = 'pi0_leading_photon_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_leading_photon_energy'},]
style = 'selected_icarus'

[[figure]]
name = 'pi0_leading_photon_conv_dist'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_leading_photon_conv_dist'},]
style = 'selected_icarus'

[[figure]]
name = 'pi0_subleading_photon_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_subleading_photon_energy'},]
style = 'selected_icarus'

[[figure]]
name = 'pi0_subleading_photon_conv_dist'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_subleading_photon_conv_dist'},]
style = 'selected_icarus'

[[figure]]
name = 'pi0_momentum_mag'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_momentum_mag'},]
style = 'selected_icarus'

[[figure]]
name = 'pi0_beam_costheta'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_beam_costheta'},]
style = 'selected_icarus'

[[figure]]
name = 'pi0_mass'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'pi0_mass'},]
style = 'selected_icarus'