[samples]
[samples.mctrad]
key = "mc"
exposure_type = "pot"
trees = ['SelectedNu_TradCuts', 'SelectedCos_TradCuts']

[samples.mcphase]
key = "mc"
exposure_type = "pot"
trees = ['SelectedNu_PhaseCuts', 'SelectedCos_PhaseCuts']

[samples.mcnophase]
key = "mc"
exposure_type = "pot"
trees = ['SelectedNu_NoPhaseCuts','SelectedCos_NoPhaseCuts']

[samples.mc_nc]
key = "mc"
exposure_type = "pot"
trees = ['SelectedNu_NCCuts','SelectedCos_NCCuts']

[samples.mcsignal]
key = "mc"
exposure_type = "pot"
trees = ['signal',]

[samples.offbeam]
key = "offbeam"
exposure_type = "pot"
trees = ['selectedNu',]

[samples.onbeamphase]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['SelectedNu_PhaseCuts',]

[samples.offbeamphase]
key = "offbeam"
exposure_type = "livetime"
override_category = -1
trees = ['SelectedCos_PhaseCuts',]

[samples.intime]
key = "intime"
exposure_type = "livetime"
trees = ['selectedCos',]