[variables]

[variables.muon_momentum_mag]
key = 'muon_momentum_mag'
range = [0,2000]
nbins = 100
xlabel = 'True Muon Momentum [MeV/c]'

[variables.pi0_leading_photon_energy]
key = 'pi0_leading_photon_energy'
range = [0,800]
nbins = 40
xlabel = 'True $\pi^{0}$ Leading Photon Energy [MeV]'

[variables.pi0_momentum_mag]
key = 'pi0_momentum_mag'
range = [0,1000]
nbins = 100
xlabel = 'True $\pi^{0}$ Momentum [MeV/c]'

[variables.pi0_mass]
key = 'pi0_mass'
range = [0,400]
nbins = 40
xlabel = 'True $\pi^{0}$ Invariant Mass [MeV/c$^{2}$]'

[variables.true_neutrino_energy]
key = 'true_edep'
range = [0,6]
nbins = 30
xlabel = 'True Neutrino Energy [GeV]'