[[this_includes]]
file = 'configurations/common/variables.toml'

[[this_includes]]
file = 'configurations/common/samples.toml'
choose = {'samples' = ['mc', 'offbeam', 'onbeam']}

[[this_includes]]
file = 'configurations/common/styles.toml'

[output]
path = '/exp/icarus/app/users/mueller/spineprod/plots/dev'

[analysis]
ordinate_sample = 'onbeam'
category_branch = 'category'
category_assignment = [[0,2], [1,3,4,5], [6], [-1,7], [-100]]
category_labels = ['1$\mu$Np', 'Other CC $\nu$', 'NC $\nu$', 'Cosmic', 'Run 2 Data']
category_colors = ['C0', 'C1', 'C3', 'C4', 'C2']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'scatter']

[[figure]]
name = 'reco_visible_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_visible_energy'},]
style = 'selected_icarus'