[variables.pi0_mass]
bins = [40, 0, 400]
title = 'Selected $\nu_{\mu}$ CC $\pi^{0}$'
xlabel = 'Reconstructed Neutral Pion Mass [MeV/c$^{2}$]'
ylabel = 'Candidates'

[analysis_mc]
category_assignment = [[0], [1], [2], [3], [4], [5], [6], [7]]
category_branch = 'category_topology'
category_labels = ['1$\mu$0$\pi^{±}$1$\pi^{0}$', '1$\mu$0$\pi^{±}$1$\pi^{0}$ (OOPS)', '1$\mu$N$\pi^{±}$1$\pi^{0}$', '1$\mu$N$\pi^{±}$0$\pi^{0}$', '1$\mu$N$\pi^{0}$', 'NC 1$\pi^{0}$ ', 'Other $\nu$', 'Cosmic']
category_colors = ['#1b9e77', '#dea0fd', '#4c78a8', '#e5c494', '#e45756', '#17becf', '#f58518', '#a6761d']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram']
