[variables]

[variables.true_visible_energy]
key = "true_edep"
range = [0, 3]
nbins = 25
xlabel = "True Visible Energy [GeV]"

[variables.reco_visible_energy]
key = "reco_edep"
range = [0, 3]
nbins = 25
xlabel = "Reconstructed Visible Energy [GeV]"

[variables.true_interaction_pt]
key = "true_dpT"
range = [0,1200]
nbins = 100
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.reco_interaction_pt]
key = "reco_dpT"
range = [0,1200]
nbins = 100
xlabel = 'Reconstructed $\delta p_T$ [MeV/c]'

[variables.reco_muon_z]
key = "reco_muon_z"
range = [-100, 100]
nbins = 100
xlabel = "Reconstructed Muon End Point Z [cm]"