[input]
path = 'muon2024_sys_rev4.root'
caflist = 'input_list.txt'

[output]
path = 'muon2024_full_rev4.root'

[variations]
keys = ['var00', 'var01', 'var03m', 'var03p', 'var04', 'var05', 'var06m', 'var06p', 'var07m', 'var07p', 'var08', 'var09']
origin = 'events/'
tree = 'selectedNu'
histogram_destination = 'variations/'
result_destination = 'detsys_results/'
variable = 'reco_edep'
bins = [1, 0, 3]
nuniverses = 100000

[[tree]]
origin = 'events/mc/selectedCos'
destination = 'events/'
name = 'selectedCos'
action = 'copy'

[[tree]]
origin = 'events/offbeam/selectedCos'
destination = 'events/'
name = 'selectedOffbeamCos'
action = 'copy'

[[tree]]
origin = 'events/mc/selectedNu'
destination = 'events/'
name = 'selectedNu'
action = 'add_weights'
table = ['multisim', 'multisigma', 'detsys']
table_type = ['weights', 'weights', 'variation']

# TPC Signal Shape
[[detsys]]
name = 'var01'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var01', 'var01', 'var01', 'var00', 'var01', 'var01', 'var01']
scale = [-3, -2, -1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# TPC IND1 Gain
[[detsys]]
name = 'var03'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var03m', 'var03m', 'var03m', 'var00', 'var03p', 'var03p', 'var03p']
scale = [3, 2, 1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# PMT Decreased QE
[[detsys]]
name = 'var04'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var04', 'var04', 'var04', 'var00', 'var04', 'var04', 'var04']
scale = [-3, -2, -1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# Ellipsoidal Recombination
[[detsys]]
name = 'var05'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var05', 'var05', 'var05', 'var00', 'var05', 'var05', 'var05']
scale = [-3, -2, -1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# TPC Coherent Noise
[[detsys]]
name = 'var06'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var06m', 'var06m', 'var06m', 'var00', 'var06p', 'var06p', 'var06p']
scale = [3, 2, 1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# TPC Intrinsic Noise
[[detsys]]
name = 'var07'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var07m', 'var07m', 'var07m', 'var00', 'var07p', 'var07p', 'var07p']
scale = [3, 2, 1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# Electron Lifetime (8ms)
[[detsys]]
name = 'var08'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var08', 'var08', 'var08', 'var00', 'var08', 'var08', 'var08']
scale = [-3, -2, -1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

# Null Variation
[[detsys]]
name = 'var09'
destination = 'events/detsys/'
ordinate = 'var00'
points = ['var09', 'var09', 'var09', 'var00', 'var09', 'var09', 'var09']
scale = [-3, -2, -1, 1, 1, 2, 3]
zscores = [-3, -2, -1, 0, 1, 2, 3]

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_ZExpA1CCQE'
index = 0

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_ZExpA2CCQE'
index = 1

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_ZExpA3CCQE'
index = 2

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_ZExpA4CCQE'
index = 3

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_VecFFCCQEshape'
index = 4

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_RPA_CCQE'
index = 5

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_CoulombCCQE'
index = 6

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NormCCMEC'
index = 7

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NormNCMEC'
index = 8

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_DecayAngMEC'
index = 9

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MaNCEL'
index = 10

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_EtaNCEL'
index = 11

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MaCCRES'
index = 12

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MvCCRES'
index = 13

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MaNCRES'
index = 14

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MvNCRES'
index = 15

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvpCC1pi'
index = 16

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvpCC2pi'
index = 17

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvpNC1pi'
index = 18

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvpNC2pi'
index = 19

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvnCC1pi'
index = 20

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvnCC2pi'
index = 21

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvnNC1pi'
index = 22

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvnNC2pi'
index = 23

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpCC1pi'
index = 24

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpCC2pi'
index = 25

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpNC1pi'
index = 26

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpNC2pi'
index = 27

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnCC1pi'
index = 28

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnCC2pi'
index = 29

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnNC1pi'
index = 30

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnNC2pi'
index = 31

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_RDecBR1gamma'
index = 32

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_RDecBR1eta'
index = 33

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_Theta_Delta2Npi'
index = 34

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_ThetaDelta2NRad'
index = 35

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NormCCCOH'
index = 36

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_NormNCCOH'
index = 37

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_AhtBY'
index = 38

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_BhtBY'
index = 39

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_CV1uBY'
index = 40

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_CV2uBY'
index = 41

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MFP_pi'
index = 42

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrCEx_pi'
index = 43

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrInel_pi'
index = 44

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrAbs_pi'
index = 45

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrPiProd_pi'
index = 46

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_MFP_N'
index = 47

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrCEx_N'
index = 48

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrInel_N'
index = 49

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrAbs_N'
index = 50

[[multisigma]]
name = 'GENIEReWeight_SBN_v1_multisigma_FrPiProd_N'
index = 51

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_ZExpAVariationResponse'
index = 52

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_RPA_CCQE'
index = 53

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_CoulombCCQE'
index = 54

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NormCCMEC'
index = 55

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NormNCMEC'
index = 56

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NCELVariationResponse'
index = 57

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_CCRESVariationResponse'
index = 58

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NCRESVariationResponse'
index = 59

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvpCC1pi'
index = 60

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvpCC2pi'
index = 61

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvpNC1pi'
index = 62

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvpNC2pi'
index = 63

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvnCC1pi'
index = 64

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvnCC2pi'
index = 65

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvnNC1pi'
index = 66

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvnNC2pi'
index = 67

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarpCC1pi'
index = 68

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarpCC2pi'
index = 69

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarpNC1pi'
index = 70

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarpNC2pi'
index = 71

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarnCC1pi'
index = 72

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarnCC2pi'
index = 73

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarnNC1pi'
index = 74

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_NonRESBGvbarnNC2pi'
index = 75

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_RDecBR1gamma'
index = 76

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_RDecBR1eta'
index = 77

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_COHVariationResponse'
index = 78

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_DISBYVariationResponse'
index = 79

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_FSI_pi_VariationResponse'
index = 80

[[multisim]]
name = 'GENIEReWeight_SBN_v1_multisim_FSI_N_VariationResponse'
index = 81

[[multisim]]
name = 'expskin_Flux'
index = 115

[[multisim]]
name = 'horncurrent_Flux'
index = 116

[[multisim]]
name = 'kminus_Flux'
index = 117

[[multisim]]
name = 'kplus_Flux'
index = 118

[[multisim]]
name = 'kzero_Flux'
index = 119

[[multisim]]
name = 'nucleoninexsec_Flux'
index = 120

[[multisim]]
name = 'nucleonqexsec_Flux'
index = 121

[[multisim]]
name = 'nucleontotxsec_Flux'
index = 122

[[multisim]]
name = 'piminus_Flux'
index = 123

[[multisim]]
name = 'pioninexsec_Flux'
index = 124

[[multisim]]
name = 'pionqexsec_Flux'
index = 125

[[multisim]]
name = 'piontotxsec_Flux'
index = 126

[[multisim]]
name = 'piplus_Flux'
index = 127